language: java
jdk:
  - openjdk8
notifications:
  email: true
jobs:
  include:
  - stage: test
    script:
    - cd Bookbnb
    - ./gradlew clean
    - ./gradlew test
  - stage: deploy
    if: branch = main
    script: npm run deploy
