language: android
jdk: openjdk8
notifications:
  email: true
android:
  components:
    - add-on
    - extra
before_install:
  - cd Bookbnb
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
jobs:
  include:
  - stage: test
    script:
    - cd Bookbnb
    - ./gradlew test
  - stage: deploy
    if: branch = main
    script: npm run deploy
